/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_IO_Abstraction.h
 * Generated on: Wed Nov 8 13:59:41 MSK
 ********************************************************************/

#ifndef RTE_SWC_IO_ABSTRACTION_H
#define RTE_SWC_IO_ABSTRACTION_H

#include "Rte_SWC_IO_Abstraction_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC_IO_Abstraction * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC_IO_Abstraction * const Rte_Inst_SWC_IO_Abstraction;

/************************ application errors *************************/

#define RTE_E_CS_IF_Set_LED_State_E_NOK ((Std_ReturnType)0)
#define RTE_E_CS_IF_Set_LED_State_E_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_sDoorState
 * Interface:	SR_IF_sSensorState
 * DataElement:	VAR_u8sDoorSensorReading
 * Runnable:	ReadDoorSensor_Runnable
 *****************************************************/
extern void Rte_IWrite_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading (uint8 VAR_u8sDoorSensorReading);
#ifndef IN_RTE_C
#define Rte_IWrite_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(RTEData) \
	Rte_IWrite_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(RTEData)
#endif
extern uint8* Rte_IWriteRef_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading() \
	Rte_IWriteRef_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading()
#endif

/*****************************************************
 * Port: 		PP_sLED_OP
 * Interface:	CS_IF_Set_LED_State
 * Operation:	OP_setLedState
 *****************************************************/
extern Std_ReturnType LedSwitch_Runnable(uint8 ARG_u8LedState) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	ReadDoorSensor_Runnable
 * Period:		0.01
 *****************************************************/
extern void ReadDoorSensor_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_IO_ABSTRACTION_H */
