/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorLockIndicatorAlgo.h
 * Generated on: Wed Nov 8 13:59:41 MSK
 ********************************************************************/

#ifndef RTE_SWC_DOORLOCKINDICATORALGO_H
#define RTE_SWC_DOORLOCKINDICATORALGO_H

#include "Rte_SWC_DoorLockIndicatorAlgo_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC_DoorLockIndicatorAlgo * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC_DoorLockIndicatorAlgo * const Rte_Inst_SWC_DoorLockIndicatorAlgo;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_LedState
 * Interface:	SR_IF_LED_State
 * DataElement:	VAR_u8LedState
 * Runnable:	DoorLock_Indicator_Runnable
 *****************************************************/
extern void Rte_IWrite_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState (uint8 VAR_u8LedState);
#ifndef IN_RTE_C
#define Rte_IWrite_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState(RTEData) \
	Rte_IWrite_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState(RTEData)
#endif
extern uint8* Rte_IWriteRef_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState() \
	Rte_IWriteRef_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState()
#endif

/*****************************************************
 * Port: 		RP_DoorState
 * Interface:	SR_IF_DoorState
 * DataElement:	VAR_u8DoorState
 * Runnable:	DoorLock_Indicator_Runnable
 *****************************************************/
extern uint8 Rte_IRead_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState (void);
#ifndef IN_RTE_C
#define Rte_IRead_DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState() \
	Rte_IRead_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	DoorLock_Indicator_Runnable
 * Period:		0.015
 *****************************************************/
extern void DoorLock_Indicator_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_DOORLOCKINDICATORALGO_H */
