/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC_DoorLockIndicatorAlgo_.c
 * Generated on: Wed Nov 8 14:0:37 MSK
 ********************************************************************/

#include "string.h"
#include "ARUnit_SWC_DoorLockIndicatorAlgo.h"


extern const Rte_CDS_SWC_DoorLockIndicatorAlgo Rte_Instance_SWC_DoorLockIndicatorAlgo;
extern const Rte_CDS_SWC_DoorLockIndicatorAlgo * const Rte_Inst_SWC_DoorLockIndicatorAlgo;




DECLSPEC_EXPORT void ARUnit_IWrite_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState(uint8 VAR_u8LedState)
{
		(Rte_Inst_SWC_DoorLockIndicatorAlgo)->DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState->value = VAR_u8LedState;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState(void)
{
	return &(Rte_Inst_SWC_DoorLockIndicatorAlgo)->DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState(void)
{
	return (Rte_Inst_SWC_DoorLockIndicatorAlgo)->DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState->value;
}
DECLSPEC_EXPORT void ARUnit_IWrite_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState(uint8 VAR_u8DoorState)
{
	(Rte_Inst_SWC_DoorLockIndicatorAlgo)->DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState->value = VAR_u8DoorState;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState(void)
{
	return &(Rte_Inst_SWC_DoorLockIndicatorAlgo)->DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState(void)
{
	return (Rte_Inst_SWC_DoorLockIndicatorAlgo)->DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState->value;
}


DECLSPEC_EXPORT void ARUnit_Trigger_SWC_DoorLockIndicatorAlgo_DoorLock_Indicator_Runnable(void)
{
	DoorLock_Indicator_Runnable();
}
