/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC_IO_Abstraction_.c
 * Generated on: Wed Nov 8 14:0:37 MSK
 ********************************************************************/

#include "string.h"
#include "ARUnit_SWC_IO_Abstraction.h"


extern const Rte_CDS_SWC_IO_Abstraction Rte_Instance_SWC_IO_Abstraction;
extern const Rte_CDS_SWC_IO_Abstraction * const Rte_Inst_SWC_IO_Abstraction;




DECLSPEC_EXPORT void ARUnit_IWrite_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(uint8 VAR_u8sDoorSensorReading)
{
		(Rte_Inst_SWC_IO_Abstraction)->ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading->value = VAR_u8sDoorSensorReading;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(void)
{
	return &(Rte_Inst_SWC_IO_Abstraction)->ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(void)
{
	return (Rte_Inst_SWC_IO_Abstraction)->ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading->value;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_SWC_IO_Abstraction_LedSwitch_Runnable(uint8 ARG_u8LedState)
{
	return LedSwitch_Runnable(ARG_u8LedState);
}


DECLSPEC_EXPORT void ARUnit_Trigger_SWC_IO_Abstraction_ReadDoorSensor_Runnable(void)
{
	ReadDoorSensor_Runnable();
}
