/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC_IO_Abstraction.h
 * Generated on: Wed Nov 8 14:0:37 MSK
 ********************************************************************/

#include "Rte_SWC_IO_Abstraction.h"	

#ifndef ARUNIT_SWC_IO_ABSTRACTION_H
#define ARUNIT_SWC_IO_ABSTRACTION_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(uint8 VAR_u8sDoorSensorReading);
DECLSPEC_EXPORT uint8 ARUnit_IRead_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(void);
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SWC_IO_Abstraction_ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_SWC_IO_Abstraction_LedSwitch_Runnable(uint8 ARG_u8LedState);

DECLSPEC_EXPORT void ARUnit_Trigger_SWC_IO_Abstraction_ReadDoorSensor_Runnable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_SWC_IO_ABSTRACTION_H */
