/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_LED_Actuator_.c
 * Generated on: Wed Nov 8 14:0:37 MSK
 ********************************************************************/

#include "string.h"
#include "Rte_SWC_LED_Actuator.h"


Rte_DE_uint8 setLedState_Runnable_RP_LedState_VAR_u8LedState;


const Rte_CDS_SWC_LED_Actuator Rte_Instance_SWC_LED_Actuator = {
&setLedState_Runnable_RP_LedState_VAR_u8LedState
};

const Rte_CDS_SWC_LED_Actuator * const Rte_Inst_SWC_LED_Actuator = &Rte_Instance_SWC_LED_Actuator;


Std_ReturnType SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Buffer_retcode = RTE_E_OK;

FunctionPtr_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Delegate = 0;

uint8 Rte_IRead_SWC_LED_Actuator_setLedState_Runnable_RP_LedState_VAR_u8LedState (void)
{
	return (Rte_Inst_SWC_LED_Actuator)->setLedState_Runnable_RP_LedState_VAR_u8LedState->value;
}
Std_ReturnType Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState (uint8 ARG_u8LedState)
{
	Std_ReturnType __result = SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Buffer_retcode;
	if ( Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Delegate != 0 ) {
		__result = Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Delegate(ARG_u8LedState);
	}
	return __result;
}
