/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorState.h
 * Generated on: Wed Nov 8 14:0:37 MSK
 ********************************************************************/

#ifndef RTE_SWC_DOORSTATE_H
#define RTE_SWC_DOORSTATE_H

#include "Rte_SWC_DoorState_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC_DoorState * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC_DoorState * const Rte_Inst_SWC_DoorState;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_DoorState
 * Interface:	SR_IF_DoorState
 * DataElement:	VAR_u8DoorState
 * Runnable:	ReadDoorState_Runnable
 *****************************************************/
extern void Rte_IWrite_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState (uint8 VAR_u8DoorState);
#ifndef IN_RTE_C
#define Rte_IWrite_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(RTEData) \
	Rte_IWrite_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(RTEData)
#endif
extern uint8* Rte_IWriteRef_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState() \
	Rte_IWriteRef_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState()
#endif

/*****************************************************
 * Port: 		RP_sDoorState
 * Interface:	SR_IF_sSensorState
 * DataElement:	VAR_u8sDoorSensorReading
 * Runnable:	ReadDoorState_Runnable
 *****************************************************/
extern uint8 Rte_IRead_SWC_DoorState_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading (void);
#ifndef IN_RTE_C
#define Rte_IRead_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading() \
	Rte_IRead_SWC_DoorState_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	ReadDoorState_Runnable
 * Period:		0.012
 *****************************************************/
extern void ReadDoorState_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_DOORSTATE_H */
