/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Wed Nov 8 14:0:37 MSK
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/



/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	uint8 value;
} Rte_DE_uint8;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: SWC_DoorLockIndicatorAlgo 
 *********************************************************************/
typedef struct Rte_CDS_SWC_DoorLockIndicatorAlgo
{
	/* Data Handles section*/
	Rte_DE_uint8 *DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState;
	Rte_DE_uint8 *DoorLock_Indicator_Runnable_PP_LedState_VAR_u8LedState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC_DoorLockIndicatorAlgo;

/*********************************************************************
 * component data structure for SWC: SWC_IO_Abstraction 
 *********************************************************************/
typedef struct Rte_CDS_SWC_IO_Abstraction
{
	/* Data Handles section*/
	Rte_DE_uint8 *ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC_IO_Abstraction;

/*********************************************************************
 * component data structure for SWC: SWC_DoorState 
 *********************************************************************/
typedef struct Rte_CDS_SWC_DoorState
{
	/* Data Handles section*/
	Rte_DE_uint8 *ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading;
	Rte_DE_uint8 *ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC_DoorState;

/*********************************************************************
 * component data structure for SWC: SWC_LED_Actuator 
 *********************************************************************/
typedef struct Rte_CDS_SWC_LED_Actuator
{
	/* Data Handles section*/
	Rte_DE_uint8 *setLedState_Runnable_RP_LedState_VAR_u8LedState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC_LED_Actuator;

/*********************************************************************
 * component data structure for SWC: LedIndicator_Composite 
 *********************************************************************/
typedef struct Rte_CDS_LedIndicator_Composite
{
	/* Data Handles section*/
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
	uint8 _dummy;
} Rte_CDS_LedIndicator_Composite;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
