/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_LED_Actuator_Type.h
 * Generated on: Wed Nov 8 13:59:41 MSK
 ********************************************************************/

#ifndef RTE_SWC_LED_ACTUATOR_TYPE_H
#define RTE_SWC_LED_ACTUATOR_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define uint8_LowerLimit  (0U)
#define uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_LED_ACTUATOR_TYPE_H */
