/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_LED_Actuator.h
 * Generated on: Wed Nov 8 13:59:41 MSK
 ********************************************************************/

#ifndef RTE_SWC_LED_ACTUATOR_H
#define RTE_SWC_LED_ACTUATOR_H

#include "Rte_SWC_LED_Actuator_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC_LED_Actuator * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC_LED_Actuator * const Rte_Inst_SWC_LED_Actuator;

/************************ application errors *************************/

#define RTE_E_CS_IF_Set_LED_State_E_NOK ((Std_ReturnType)0)
#define RTE_E_CS_IF_Set_LED_State_E_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_LedState
 * Interface:	SR_IF_LED_State
 * DataElement:	VAR_u8LedState
 * Runnable:	setLedState_Runnable
 *****************************************************/
extern uint8 Rte_IRead_SWC_LED_Actuator_setLedState_Runnable_RP_LedState_VAR_u8LedState (void);
#ifndef IN_RTE_C
#define Rte_IRead_setLedState_Runnable_RP_LedState_VAR_u8LedState() \
	Rte_IRead_SWC_LED_Actuator_setLedState_Runnable_RP_LedState_VAR_u8LedState()
#endif

/*****************************************************
 * Port: 		RP_sLED_OP
 * Interface:	CS_IF_Set_LED_State
 * Operation:	OP_setLedState
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState (uint8 ARG_u8LedState);
#ifndef IN_RTE_C
#define Rte_Call_RP_sLED_OP_OP_setLedState(ARG_u8LedState) \
	Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState(ARG_u8LedState)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	setLedState_Runnable
 * Period:		0.018
 *****************************************************/
extern void setLedState_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState)(uint8 ARG_u8LedState);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_LED_ACTUATOR_H */
