/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorState_.c
 * Generated on: Wed Nov 8 13:59:41 MSK
 ********************************************************************/

#include "string.h"
#include "Rte_SWC_DoorState.h"


Rte_DE_uint8 ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading;
Rte_DE_uint8 ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState;


const Rte_CDS_SWC_DoorState Rte_Instance_SWC_DoorState = {
&ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading,
&ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState
};

const Rte_CDS_SWC_DoorState * const Rte_Inst_SWC_DoorState = &Rte_Instance_SWC_DoorState;




void Rte_IWrite_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState (uint8 VAR_u8DoorState)
{
	(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState->value = VAR_u8DoorState;
}
uint8* Rte_IWriteRef_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(void)
{
	return &(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState->value;
}
uint8 Rte_IRead_SWC_DoorState_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading (void)
{
	return (Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading->value;
}
