/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC_LED_Actuator_.c
 * Generated on: Wed Nov 8 13:59:41 MSK
 ********************************************************************/

#include "string.h"
#include "ARUnit_SWC_LED_Actuator.h"


extern const Rte_CDS_SWC_LED_Actuator Rte_Instance_SWC_LED_Actuator;
extern const Rte_CDS_SWC_LED_Actuator * const Rte_Inst_SWC_LED_Actuator;


extern Std_ReturnType SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Buffer_retcode;

extern FunctionPtr_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_SWC_LED_Actuator_setLedState_Runnable_RP_LedState_VAR_u8LedState(uint8 VAR_u8LedState)
{
	(Rte_Inst_SWC_LED_Actuator)->setLedState_Runnable_RP_LedState_VAR_u8LedState->value = VAR_u8LedState;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SWC_LED_Actuator_setLedState_Runnable_RP_LedState_VAR_u8LedState(void)
{
	return &(Rte_Inst_SWC_LED_Actuator)->setLedState_Runnable_RP_LedState_VAR_u8LedState->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SWC_LED_Actuator_setLedState_Runnable_RP_LedState_VAR_u8LedState(void)
{
	return (Rte_Inst_SWC_LED_Actuator)->setLedState_Runnable_RP_LedState_VAR_u8LedState->value;
}
DECLSPEC_EXPORT void ARUnit_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_ReturnCode(Std_ReturnType returnCode)
{
	SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Delegate(FunctionPtr_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState  delegate)
{
	Rte_Call_SWC_LED_Actuator_RP_sLED_OP_OP_setLedState_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_SWC_LED_Actuator_setLedState_Runnable(void)
{
	setLedState_Runnable();
}
