/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorState_.c
 * Generated on: Wed Nov 8 14:0:37 MSK
 ********************************************************************/

#include "string.h"
#include "Rte_SWC_DoorState.h"


Rte_DE_uint8 ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading;
Rte_DE_uint8 ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState;

/* IO_Abs Variables	*/
Rte_DE_uint8 ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading;


/*	APPSWC_Vars		*/
Rte_DE_uint8 DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState;


const Rte_CDS_SWC_DoorState Rte_Instance_SWC_DoorState = {
&ReadDoorSensor_Runnable_PP_sDoorState_VAR_u8sDoorSensorReading,
&DoorLock_Indicator_Runnable_RP_DoorState_VAR_u8DoorState
};

const Rte_CDS_SWC_DoorState * const Rte_Inst_SWC_DoorState = &Rte_Instance_SWC_DoorState;




void Rte_IWrite_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState (uint8 VAR_u8DoorState)
{
	(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState->value = VAR_u8DoorState;
}
uint8* Rte_IWriteRef_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(void)
{
	return &(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState->value;
}
uint8 Rte_IRead_SWC_DoorState_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading (void)
{
	return (Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading->value;
}
