/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC_DoorState_.c
 * Generated on: Wed Nov 8 13:59:41 MSK
 ********************************************************************/

#include "string.h"
#include "ARUnit_SWC_DoorState.h"


extern const Rte_CDS_SWC_DoorState Rte_Instance_SWC_DoorState;
extern const Rte_CDS_SWC_DoorState * const Rte_Inst_SWC_DoorState;




DECLSPEC_EXPORT void ARUnit_IWrite_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(uint8 VAR_u8DoorState)
{
		(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState->value = VAR_u8DoorState;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(void)
{
	return &(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SWC_DoorState_ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState(void)
{
	return (Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_PP_DoorState_VAR_u8DoorState->value;
}
DECLSPEC_EXPORT void ARUnit_IWrite_SWC_DoorState_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading(uint8 VAR_u8sDoorSensorReading)
{
	(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading->value = VAR_u8sDoorSensorReading;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_SWC_DoorState_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading(void)
{
	return &(Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_SWC_DoorState_ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading(void)
{
	return (Rte_Inst_SWC_DoorState)->ReadDoorState_Runnable_RP_sDoorState_VAR_u8sDoorSensorReading->value;
}


DECLSPEC_EXPORT void ARUnit_Trigger_SWC_DoorState_ReadDoorState_Runnable(void)
{
	ReadDoorState_Runnable();
}
